#pragma once
#include "Components/Layout/Objects/Line/Line.h"
#include "Components/Memory Manager/MemoryStructs.h"
#include "Components/Process Manager/Process.h"
#include "Libraries/Vector.h"

constexpr float TAB_WIDTH       = 30.f;
constexpr float LINE_HEIGHT     = 23.f;
constexpr float ELEMENT_PADDING = 10.f;

// I added a billion comments on the last rewrite of this part
// Because the last 2 times I ended up forgetting what some parts do (1.5k LoC is pretty big tbh...)

namespace Renderer::Layout
{
	class View;

	struct RenderParameters
	{
		uintptr_t BaseAddress = 0;
		uint32_t  PID         = 0;
		View*     Owner       = nullptr;

		struct
		{
			float Offset           = 0.f;
			float Address          = 0.f;
			float NamedTypeOrLabel = 0.f;
			float HexOrLabel       = 0.f;
			float Chars            = 0.f;
			float Formatted        = 0.f;
		} Columns;

		Vector2f WindowSize = Vector2f::Zero;
		float    HexWidth   = 0.f;
		float    CharWidth  = 0.f;

		bool  ScheduleRecalculate = false;
		void* Buffer              = nullptr;
	};

	struct DisassemblyCache
	{
		uint64_t                 Timestamp = 0;
		std::vector<std::string> Lines     = {};
	};

	struct LineData
	{
		// The logic here is that we can retrieve the Field Data via Source Index
		// But if this a synthetic (aka generated by the realignment), there is no source index, therefore PaddingField is used
		ptrdiff_t                    SourceIndex  = -1;
		std::optional<Memory::Field> PaddingField = std::nullopt;

		struct
		{
			bool                            Expanded    = false;
			View*                           Child       = nullptr;
			std::optional<DisassemblyCache> Disassembly = std::nullopt;
		} Embedded;

		void ClearEmbeddedData()
		{
			this->Embedded.Expanded    = false;
			this->Embedded.Child       = nullptr;
			this->Embedded.Disassembly = std::nullopt;
		}

		bool IsSynthetic() const { return SourceIndex < 0 && PaddingField.has_value(); }
	};

	struct LineSlot
	{
		LineData      Data = {};
		Objects::Line Line;

		explicit LineSlot() : Line( this )
		{
		}

		LineSlot( const LineSlot& )            = delete;
		LineSlot& operator=( const LineSlot& ) = delete;
		LineSlot& operator=( LineSlot&& )      = delete;

		LineSlot( LineSlot&& Other ) noexcept : Data( std::move( Other.Data ) ), Line( this )
		{
			Line.ExpandButton = std::move( Other.Line.ExpandButton );
		}
	};

	// These are dispatched by Objects::Line, should (probably) not be used anywhere else
	namespace Internals
	{
		void RenderFunction( Vector2f& Cursor, const RenderParameters* RenderData, LineData& Data, size_t& i );
		void RenderLine( Vector2f& Cursor, RenderParameters* RenderData, LineData& Data, Memory::Info* Template, Memory::Field* Field, size_t& i, bool IsSelected );
	}

	class Grid
	{
	public:
		static void OnAttachProcess( uint32_t PID, ProcessStatus Status );
		static void NewStructTab( const std::string& Label, uint32_t PID, uintptr_t Address, std::string_view TemplateName, std::optional<size_t> Size = std::nullopt );
		static void NewTab( const std::string& Label, uint32_t PID, uintptr_t Address, size_t Size );
		static void Present( Vector2f& Cursor, Vector2f AvailableSize, float Opacity );
		static bool WndProc( Vector2f Position, uint32_t Message, WPARAM wParam, LPARAM lParam );
		static void ChangeSelected( DataStructureType NewType );
		static void OnButtonCallback( const Objects::Button* Instance );
		// Cheap work-around to get Info* for a View without declaring the entire class here
		static std::shared_ptr<Memory::Info> GetInfoForView( const View* View );
		static void                          RenderView( View* View, Vector2f& Cursor, size_t& i );
	};
}
